@echo off
goto:rem
***************************************
This file is part of RetroBat Scripts.
---------------------------------------
file name: systemsnames.cmd
language: batch
author: Kayl 
***************************************
:rem
set amiga="amiga"
set amstradcpc="amstradcpc"
set apple2="apple2"
set arcade="arcade"
set atari2600="atari2600"
set atari5200="atari5200"
set atarijaguar="jaguar"
set atarilynx="lynx"
set ataripro="atari7800"
set atarist="atarist"
set atomiswave="atomiswave"
set cave="cave"
set colecov="colecovision"
set com64="c64"
set cps1="cps1"
set cps2="cps2"
set cps3="cps3"
set dreamcast="dreamcast"
set fba="fba"
set fds="fds"
set fpinball="fpinball"
set gamecube="gamecube"
set gamegear="gamegear"
set gamewatch="gameandwatch"
set gb="gb"
set gb2p="gb2players"
set gbadv="gba"
set gbcolor="gbc"
set gbc2p="gbc2players"
set intellivision="intellivision"
set laserdisc="laserdisc"
set mame="mame"
set mastersystem="mastersystem"
set megacd="segacd"
set megadrive="megadrive"
set model2="model2"
set msdos="dos"
set mugen="mugen"
set msu1="snes-msu"
set msx="msx"
set n64="n64"
set naomi="naomi"
set nds="nds"
set n3ds="n3ds"
set neogeo="neogeo"
set neogeocd="neogeocd"
set nes="nes"
set ngp="ngp"
set ngpc="ngpc"
set openbor="openbor"
set pce="pcengine"
set pcecd="pcenginecd"
set pcfx="pcfx"
set pcgames="windows"
set prboom="prboom"
set ps2="ps2"
set ps3="ps3"
set psp="psp"
set psx="psx"
set saturn="saturn"
set sega32x="sega32x"
set sg1000="sg1000"
set snes="snes"
set scummvm="scummvm"
set supergrafx="supergrafx"
set threedo="3do"
set thomson="thomson"
set vectrex="vectrex"
set vb="vb"
set videopac="o2em"
set vpinball="vpinball"
set wii="wii"
set wswan="wswan"
set wswanc="wswanc"
set zxspectrum="zxspectrum"
goto:eof