@echo off
goto:rem
***************************************
This file is part of RetroBat Scripts.
***************************************
:rem

for /f "delims=" %%x in (%setup_dir%\system\setup.info) do (set "%%x")
for /f "delims=" %%x in (%config_dir%\retrobat.cfg) do (set "%%x")
for /f "delims=" %%x in (%config_dir%\systems_resolutions.cfg) do (set "%%x")

set full_path=%1
set full_path=%full_path:""=%
set full_path
For %%A in ("%full_path%") do (
    Set current_rom_dir=%%~dpA
    Set current_rom_name=%%~nxA
)
Set trusted_rom_dir=%CD:~0,2%%setup_dir%\roms

if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%global_resolution_x% /Y:%global_resolution_y% >nul

if "%current_rom_dir%"=="%trusted_rom_dir%\3do\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_3do_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%3do_resolution_x% /Y:%3do_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amiga\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_amiga_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amiga_resolution_x% /Y:%amiga_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amiga500\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_amiga500_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amiga500_resolution_x% /Y:%amiga500_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amiga1200\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_1200_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amiga1200_resolution_x% /Y:%amiga1200_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amigacd32\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_amigacd32_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amigacd32_resolution_x% /Y:%amigacd32_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amigacdtv\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_amigacdtv_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amigacdtv_resolution_x% /Y:%amigacdtv_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\amstradcpc\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_amstradcpc_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%amstradcpc_resolution_x% /Y:%amstradcpc_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\arcade\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_arcade_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%arcade_resolution_x% /Y:%arcade_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\atari800\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_atari800_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%atari800_resolution_x% /Y:%atari800_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\atari2600\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_atari2600_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%atari2600_resolution_x% /Y:%atari2600_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\atari7800\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_atari7800_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%atari7800_resolution_x% /Y:%atari7800_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\atarist\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_atarist_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%atarist_resolution_x% /Y:%atarist_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\atomiswave\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_atomiswave_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%atomiswave_resolution_x% /Y:%atomiswave_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\c20\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_c20_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%c20_resolution_x% /Y:%c20_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\c64\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_c64_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%c64_resolution_x% /Y:%c64_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\c128\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_c128_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%c128_resolution_x% /Y:%c128_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\cave\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_cave_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%cave_resolution_x% /Y:%cave_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\cavestory\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_cavestory_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%cavestory_resolution_x% /Y:%cavestory_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\chihiro\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_chihiro_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%chihiro_resolution_x% /Y:%chihiro_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\colecovision\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_colecovision_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%colecovision_resolution_x% /Y:%colecovision_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\cps1\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_cps1_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%cps1_resolution_x% /Y:%cps1_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\cps2\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_cps2_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%cps2_resolution_x% /Y:%cps2_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\cps3\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_cps3_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%cps3_resolution_x% /Y:%cps3_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\daphne\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_daphne_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%daphne_resolution_x% /Y:%daphne_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\dos\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_dos_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%dos_resolution_x% /Y:%dos_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\dreamcast\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_dreamcast_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%dreamcast_resolution_x% /Y:%dreamcast_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\fba\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_fba_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%fba_resolution_x% /Y:%fba_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\fds\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_fds_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%fds_resolution_x% /Y:%fds_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gaelco\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gaelco_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gaelco_resolution_x% /Y:%gaelco_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gameandwatch\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gameandwatch_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gameandwatch_resolution_x% /Y:%gameandwatch_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gamecube\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gamecube_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gamecube_resolution_x% /Y:%gamecube_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gamegear\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gamegear_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gamegear_resolution_x% /Y:%gamegear_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gb\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gb_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gb_resolution_x% /Y:%gb_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gb2players\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gb2players_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gb2players_resolution_x% /Y:%gb2players_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gba\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gba_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gba_resolution_x% /Y:%gba_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gbc\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gbc_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gbc_resolution_x% /Y:%gbc_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gbc2players\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gbc2players_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gbc2players_resolution_x% /Y:%gbc2players_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\gx4000\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_gx4000_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%gx4000_resolution_x% /Y:%gx4000_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\hikaru\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_hikaru_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%hikaru_resolution_x% /Y:%hikaru_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\intellivision\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_intellivision_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%intellivision_resolution_x% /Y:%intellivision_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\jaguar\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_jaguar_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%jaguar_resolution_x% /Y:%jaguar_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\lightgun\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_lightgun_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%lightgun_resolution_x% /Y:%lightgun_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\lutro\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_lutro_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%lutro_resolution_x% /Y:%lutro_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\lynx\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_lynx_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%lynx_resolution_x% /Y:%lynx_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\mame\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_mame_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%mame_resolution_x% /Y:%mame_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\mastersystem\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_mastersystem_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%mastersystem_resolution_x% /Y:%mastersystem_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\megadrive\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_megadrive_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%megadrive_resolution_x% /Y:%megadrive_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\model2\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_model2_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%model2_resolution_x% /Y:%model2_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\model3\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_model3_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%model3_resolution_x% /Y:%model3_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\msx\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_msx_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%msx_resolution_x% /Y:%msx_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\msx1\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_msx1_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%msx1_resolution_x% /Y:%msx1_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\msx2\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_msx2_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%msx2_resolution_x% /Y:%msx2_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\msx2+\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_msx2plus_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%msx2plus_resolution_x% /Y:%msx2plus_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\n3ds\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_n3ds_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%n3ds_resolution_x% /Y:%n3ds_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\n64\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_n64_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%n64_resolution_x% /Y:%n64_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\naomi\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_naomi_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%naomi_resolution_x% /Y:%naomi_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\naomi2\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_naomi2_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%naomi2_resolution_x% /Y:%naomi2_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\nds\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_nds_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%nds_resolution_x% /Y:%nds_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\neogeo\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_neogeo_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%neogeo_resolution_x% /Y:%neogeo_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\neogeocd\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_neogeocd_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%neogeocd_resolution_x% /Y:%neogeocd_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\nes\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_nes_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%nes_resolution_x% /Y:%nes_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\ngp\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_ngp_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%ngpc_resolution_x% /Y:%ngpc_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\ngpc\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_ngpc_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%ngpc_resolution_x% /Y:%ngpc_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\o2em\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_o2em_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%o2em_resolution_x% /Y:%o2em_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\pc98\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_pc98_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%pc98_resolution_x% /Y:%pc98_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\pcengine\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_pcengine_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%pcengine_resolution_x% /Y:%pcengine_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\pcenginecd\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_pcenginecd_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%pcenginecd_resolution_x% /Y:%pcenginecd_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\pcfx\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_pcfx_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%pcfx_resolution_x% /Y:%pcfx_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\pokemini\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_pokemini_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%pokemini_resolution_x% /Y:%pokemini_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\ps2\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_ps2_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%ps2_resolution_x% /Y:%ps2_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\ps3\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_ps3_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%ps3_resolution_x% /Y:%ps3_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\psp\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_psp_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%psp_resolution_x% /Y:%psp_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\psx\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_psx_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%psx_resolution_x% /Y:%psx_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\samcoupe\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_samcoupe_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%samcoupe_resolution_x% /Y:%samcoupe_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\saturn\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_saturn_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%saturn_resolution_x% /Y:%saturn_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\satellaview\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_satellaview_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%satellaview_resolution_x% /Y:%satellaview_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\scummvm\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_scummvm_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%scummvm_resolution_x% /Y:%scummvm_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\sega32x\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_sega32x_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%sega32x_resolution_x% /Y:%sega32x_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\segacd\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_segacd_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%segacd_resolution_x% /Y:%segacd_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\sg1000\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_sg1000_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%sg1000_resolution_x% /Y:%sg1000_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\snes\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_snes_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%snes_resolution_x% /Y:%snes_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\snes-msu\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_snesmsu_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%snesmsu_resolution_x% /Y:%snesmsu_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\sufami\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_sufami_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%sufami_resolution_x% /Y:%sufami_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\supergrafx\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_supergrafx_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%supergrafx_resolution_x% /Y:%supergrafx_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\switch\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_switch_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%switch_resolution_x% /Y:%switch_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\thomson\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_thomson_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%thomson_resolution_x% /Y:%thomson_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\triforce\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_triforce_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%triforce_resolution_x% /Y:%triforce_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\vectrex\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_vectrex_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%vectrex_resolution_x% /Y:%vectrex_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\virtualboy\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_virtualboy_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%virtualboy_resolution_x% /Y:%virtualboy_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\wii\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_wii_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%wii_resolution_x% /Y:%wii_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\wswan\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_wswan_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%wswan_resolution_x% /Y:%wswan_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\wswanc\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_wswanc_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%wswanc_resolution_x% /Y:%wswanc_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\x68000\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_x68000_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%x68000_resolution_x% /Y:%x68000_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\xbox\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_xbox_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%xbox_resolution_x% /Y:%xbox_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\xbox360\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_xbox360_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%xbox360_resolution_x% /Y:%xbox360_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\zxspectrum\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_zxspectrum_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%zxspectrum_resolution_x% /Y:%zxspectrum_resolution_y% >nul
if "%current_rom_dir%"=="%trusted_rom_dir%\zx81\" if "%set_screen_resolution%"=="1" if "%set_global_resolution%"=="0" if "%set_zx81_resolution%"=="1" %setup_dir%\system\modules\qres.exe /X:%zx81_resolution_x% /Y:%zx81_resolution_y% >nul
exit