 local f = io.open(".\templates\es_systems_editable.cfg", "r")
 local content = f:read("*all")
 f:close()
 content = string.gsub(content, "$SETROMSPATH", "~\..")
 local f = io.open(".\templates\es_systems_retrobat.cfg", "w")
 f:write(content)
 f:close()